export const environment = {
  format_url: 'https://tanstudyapi.onrender.com/api/formats',
  topic_url: 'https://tanstudyapi.onrender.com/api/topics',
  subtopic_url: 'https://tanstudyapi.onrender.com/api/subtopics',
  question_url: 'https://tanstudyapi.onrender.com/api/questions',
  login_url: 'https://tanstudyapi.onrender.com/api/users',
  quote_url: 'https://tanstudyapi.onrender.com/api/quotes',
  diary_url: 'https://tanstudyapi.onrender.com/api/diaries',
  review_url: 'https://tanstudyapi.onrender.com/api/reviews',
  plan_url: 'https://tanstudyapi.onrender.com/api/plans',
  thought_url: 'https://tanstudyapi.onrender.com/api/thoughts',
  field_url: 'https://tanstudyapi.onrender.com/api/fields',
  todo_url: 'https://tanstudyapi.onrender.com/api/todos',
  login_page: '/login',
};
